/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as WeekendRouteImport } from './routes/weekend'
import { Route as WhyRouteImport } from './routes/why'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as EditionsYearRouteImport } from './routes/editions.$year'
import { Route as ApiPublicCalendarDoticsRouteImport } from './routes/api/public/calendar[.]ics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendRoute = WeekendRouteImport.update({
  id: '/weekend',
  path: '/weekend',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EditionsYearRoute = EditionsYearRouteImport.update({
  id: '/editions/$year',
  path: '/editions/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarDoticsRoute = ApiPublicCalendarDoticsRouteImport.update({
  id: '/api/public/calendar.ics',
  path: '/api/public/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/weekend': typeof WeekendRoute
  '/why': typeof WhyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/editions/$year': typeof EditionsYearRoute
  '/api/public/calendar.ics': typeof ApiPublicCalendarDoticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/weekend': typeof WeekendRoute
  '/why': typeof WhyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/editions/$year': typeof EditionsYearRoute
  '/api/public/calendar.ics': typeof ApiPublicCalendarDoticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/weekend': typeof WeekendRoute
  '/why': typeof WhyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/editions/$year': typeof EditionsYearRoute
  '/api/public/calendar.ics': typeof ApiPublicCalendarDoticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/weekend'
    | '/why'
    | '/admin'
    | '/me'
    | '/editions/$year'
    | '/api/public/calendar.ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/weekend'
    | '/why'
    | '/admin'
    | '/me'
    | '/editions/$year'
    | '/api/public/calendar.ics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/weekend'
    | '/why'
    | '/_authenticated/admin'
    | '/_authenticated/me'
    | '/editions/$year'
    | '/api/public/calendar.ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  WeekendRoute: typeof WeekendRoute
  WhyRoute: typeof WhyRoute
  EditionsYearRoute: typeof EditionsYearRoute
  ApiPublicCalendarDoticsRoute: typeof ApiPublicCalendarDoticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend': {
      id: '/weekend'
      path: '/weekend'
      fullPath: '/weekend'
      preLoaderRoute: typeof WeekendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/editions/$year': {
      id: '/editions/$year'
      path: '/editions/$year'
      fullPath: '/editions/$year'
      preLoaderRoute: typeof EditionsYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar.ics': {
      id: '/api/public/calendar.ics'
      path: '/api/public/calendar.ics'
      fullPath: '/api/public/calendar.ics'
      preLoaderRoute: typeof ApiPublicCalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  WeekendRoute: WeekendRoute,
  WhyRoute: WhyRoute,
  EditionsYearRoute: EditionsYearRoute,
  ApiPublicCalendarDoticsRoute: ApiPublicCalendarDoticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
