/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as WeekendRouteImport } from './routes/weekend'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as EditionsYearRouteImport } from './routes/editions.$year'
import { Route as ApiPhotosUploadRouteImport } from './routes/api/photos/upload'
import { Route as ApiPublicCalendarDoticsRouteImport } from './routes/api/public/calendar[.]ics'
import { Route as ApiPublicHeadcountRouteImport } from './routes/api/public/headcount'
import { Route as ApiPublicResendWebhookRouteImport } from './routes/api/public/resend-webhook'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as ApiPublicPhotoSplatRouteImport } from './routes/api/public/photo/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendRoute = WeekendRouteImport.update({
  id: '/weekend',
  path: '/weekend',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsYearRoute = EditionsYearRouteImport.update({
  id: '/editions/$year',
  path: '/editions/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosUploadRoute = ApiPhotosUploadRouteImport.update({
  id: '/api/photos/upload',
  path: '/api/photos/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarDoticsRoute = ApiPublicCalendarDoticsRouteImport.update({
  id: '/api/public/calendar.ics',
  path: '/api/public/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeadcountRoute = ApiPublicHeadcountRouteImport.update({
  id: '/api/public/headcount',
  path: '/api/public/headcount',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResendWebhookRoute = ApiPublicResendWebhookRouteImport.update({
  id: '/api/public/resend-webhook',
  path: '/api/public/resend-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPhotoSplatRoute = ApiPublicPhotoSplatRouteImport.update({
  id: '/api/public/photo/$',
  path: '/api/public/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/auth': typeof AuthRoute
  '/weekend': typeof WeekendRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editions/$year': typeof EditionsYearRoute
  '/api/photos/upload': typeof ApiPhotosUploadRoute
  '/api/public/calendar.ics': typeof ApiPublicCalendarDoticsRoute
  '/api/public/headcount': typeof ApiPublicHeadcountRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/auth': typeof AuthRoute
  '/weekend': typeof WeekendRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/editions/$year': typeof EditionsYearRoute
  '/api/photos/upload': typeof ApiPhotosUploadRoute
  '/api/public/calendar.ics': typeof ApiPublicCalendarDoticsRoute
  '/api/public/headcount': typeof ApiPublicHeadcountRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alumni': typeof AlumniRoute
  '/auth': typeof AuthRoute
  '/weekend': typeof WeekendRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/editions/$year': typeof EditionsYearRoute
  '/api/photos/upload': typeof ApiPhotosUploadRoute
  '/api/public/calendar.ics': typeof ApiPublicCalendarDoticsRoute
  '/api/public/headcount': typeof ApiPublicHeadcountRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumni'
    | '/auth'
    | '/weekend'
    | '/admin'
    | '/me'
    | '/auth/callback'
    | '/editions/$year'
    | '/api/photos/upload'
    | '/api/public/calendar.ics'
    | '/api/public/headcount'
    | '/api/public/resend-webhook'
    | '/api/public/unsubscribe'
    | '/api/public/photo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alumni'
    | '/auth'
    | '/weekend'
    | '/admin'
    | '/me'
    | '/auth/callback'
    | '/editions/$year'
    | '/api/photos/upload'
    | '/api/public/calendar.ics'
    | '/api/public/headcount'
    | '/api/public/resend-webhook'
    | '/api/public/unsubscribe'
    | '/api/public/photo/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alumni'
    | '/auth'
    | '/weekend'
    | '/_authenticated/admin'
    | '/_authenticated/me'
    | '/auth_/callback'
    | '/editions/$year'
    | '/api/photos/upload'
    | '/api/public/calendar.ics'
    | '/api/public/headcount'
    | '/api/public/resend-webhook'
    | '/api/public/unsubscribe'
    | '/api/public/photo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlumniRoute: typeof AlumniRoute
  AuthRoute: typeof AuthRoute
  WeekendRoute: typeof WeekendRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EditionsYearRoute: typeof EditionsYearRoute
  ApiPhotosUploadRoute: typeof ApiPhotosUploadRoute
  ApiPublicCalendarDoticsRoute: typeof ApiPublicCalendarDoticsRoute
  ApiPublicHeadcountRoute: typeof ApiPublicHeadcountRoute
  ApiPublicResendWebhookRoute: typeof ApiPublicResendWebhookRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiPublicPhotoSplatRoute: typeof ApiPublicPhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend': {
      id: '/weekend'
      path: '/weekend'
      fullPath: '/weekend'
      preLoaderRoute: typeof WeekendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions/$year': {
      id: '/editions/$year'
      path: '/editions/$year'
      fullPath: '/editions/$year'
      preLoaderRoute: typeof EditionsYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos/upload': {
      id: '/api/photos/upload'
      path: '/api/photos/upload'
      fullPath: '/api/photos/upload'
      preLoaderRoute: typeof ApiPhotosUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar.ics': {
      id: '/api/public/calendar.ics'
      path: '/api/public/calendar.ics'
      fullPath: '/api/public/calendar.ics'
      preLoaderRoute: typeof ApiPublicCalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/headcount': {
      id: '/api/public/headcount'
      path: '/api/public/headcount'
      fullPath: '/api/public/headcount'
      preLoaderRoute: typeof ApiPublicHeadcountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resend-webhook': {
      id: '/api/public/resend-webhook'
      path: '/api/public/resend-webhook'
      fullPath: '/api/public/resend-webhook'
      preLoaderRoute: typeof ApiPublicResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/photo/$': {
      id: '/api/public/photo/$'
      path: '/api/public/photo/$'
      fullPath: '/api/public/photo/$'
      preLoaderRoute: typeof ApiPublicPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlumniRoute: AlumniRoute,
  AuthRoute: AuthRoute,
  WeekendRoute: WeekendRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EditionsYearRoute: EditionsYearRoute,
  ApiPhotosUploadRoute: ApiPhotosUploadRoute,
  ApiPublicCalendarDoticsRoute: ApiPublicCalendarDoticsRoute,
  ApiPublicHeadcountRoute: ApiPublicHeadcountRoute,
  ApiPublicResendWebhookRoute: ApiPublicResendWebhookRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiPublicPhotoSplatRoute: ApiPublicPhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
