CREATE TABLE public.divisions (
  code text PRIMARY KEY,
  label text NOT NULL,
  sort_order int NOT NULL
);
GRANT SELECT ON public.divisions TO anon, authenticated;
GRANT ALL ON public.divisions TO service_role;
ALTER TABLE public.divisions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "divisions readable by everyone" ON public.divisions FOR SELECT TO anon, authenticated USING (true);

INSERT INTO public.divisions (code, label, sort_order) VALUES
  ('MENS_A', 'Men''s A', 1),
  ('MENS_B', 'Men''s B', 2),
  ('WOMENS_A', 'Women''s A', 3),
  ('WOMENS_B', 'Women''s B', 4);

CREATE TABLE public.team_names (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  division text NOT NULL REFERENCES public.divisions(code),
  name text,
  start_year int,
  end_year int,
  confidence text NOT NULL CHECK (confidence IN ('verified','assumed','unknown'))
);
CREATE INDEX team_names_division_start_year_idx ON public.team_names (division, start_year);
GRANT SELECT ON public.team_names TO anon, authenticated;
GRANT ALL ON public.team_names TO service_role;
ALTER TABLE public.team_names ENABLE ROW LEVEL SECURITY;
CREATE POLICY "team names readable by everyone" ON public.team_names FOR SELECT TO anon, authenticated USING (true);

INSERT INTO public.team_names (division, name, start_year, end_year, confidence) VALUES
  ('MENS_A', NULL, 1978, 1997, 'unknown'),
  ('MENS_A', 'En Sabah Nur', 1998, NULL, 'verified'),
  ('MENS_B', 'Sabah B', 2005, 2009, 'assumed'),
  ('MENS_B', 'BITT', 2010, 2024, 'assumed'),
  ('MENS_B', 'Pressure', 2025, NULL, 'verified'),
  ('WOMENS_A', 'Pansy', 1998, 2005, 'assumed'),
  ('WOMENS_A', 'Danger', 2006, NULL, 'assumed'),
  ('WOMENS_B', 'Danger B', 1998, NULL, 'assumed');

CREATE TABLE public.people (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  member_no bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 100001),
  seed_id text UNIQUE,
  first_name text NOT NULL,
  last_name text,
  played_as text,
  current_city text,
  grad_year int,
  seed_division text REFERENCES public.divisions(code),
  seed_division_alt text REFERENCES public.divisions(code),
  deceased boolean NOT NULL DEFAULT false,
  deceased_note text,
  deceased_confirmed_by uuid REFERENCES public.people(id),
  deceased_confirmed_at timestamptz,
  show_on_board boolean NOT NULL DEFAULT true,
  share_email boolean NOT NULL DEFAULT false,
  open_to_network boolean NOT NULL DEFAULT false,
  needs_review boolean NOT NULL DEFAULT false,
  is_anchor boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX people_grad_year_idx ON public.people (grad_year);
CREATE INDEX people_lower_first_name_idx ON public.people (lower(first_name));
CREATE INDEX people_lower_last_name_idx ON public.people (lower(last_name));

CREATE TABLE public.identities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
  email text NOT NULL UNIQUE CHECK (email = lower(email)),
  auth_user_id uuid UNIQUE,
  provider text NOT NULL CHECK (provider IN ('seed','magic','google')),
  is_primary boolean NOT NULL DEFAULT false,
  verified_at timestamptz,
  created_at timestamptz DEFAULT now()
);
CREATE UNIQUE INDEX identities_one_primary_per_person ON public.identities (person_id) WHERE is_primary;
CREATE INDEX identities_person_id_idx ON public.identities (person_id);

CREATE TABLE public.stints (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
  division text NOT NULL REFERENCES public.divisions(code),
  role text NOT NULL DEFAULT 'player' CHECK (role IN ('player','captain','coach','manager')),
  year int NOT NULL CHECK (year BETWEEN 1970 AND 2100),
  confirmed_by uuid REFERENCES public.people(id),
  confirmed_at timestamptz,
  source text NOT NULL CHECK (source IN ('esn_alumni_page','roster_import','self','admin')),
  created_at timestamptz DEFAULT now(),
  UNIQUE (person_id, division, year, role)
);
CREATE INDEX stints_person_id_idx ON public.stints (person_id);
CREATE INDEX stints_year_division_idx ON public.stints (year, division);

CREATE TABLE public.events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_year int NOT NULL,
  day_number int CHECK (day_number BETWEEN 1 AND 7),
  title text NOT NULL,
  starts_at timestamptz,
  ends_at timestamptz,
  time_tbd boolean NOT NULL DEFAULT true,
  location text,
  division text REFERENCES public.divisions(code),
  notes text,
  sort_order int NOT NULL DEFAULT 0
);

CREATE TABLE public.rsvps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
  event_year int NOT NULL,
  status text NOT NULL CHECK (status IN ('going','maybe','not_this_year')),
  src text CHECK (src IN ('discord','groupme','email')),
  responded_at timestamptz DEFAULT now(),
  UNIQUE (person_id, event_year)
);

CREATE TABLE public.suggestions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  submitted_by uuid NOT NULL REFERENCES public.people(id),
  type text NOT NULL CHECK (type IN ('new_person','edit','memorial','roster_import')),
  payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  peer_verified_by uuid REFERENCES public.people(id),
  reviewed_by uuid REFERENCES public.people(id),
  reviewed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.verifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
  verified_by uuid NOT NULL REFERENCES public.people(id),
  created_at timestamptz DEFAULT now(),
  UNIQUE (person_id, verified_by)
);

CREATE TABLE public.admins (
  person_id uuid PRIMARY KEY REFERENCES public.people(id) ON DELETE CASCADE
);

CREATE TABLE public.audit_log (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  actor_person_id uuid REFERENCES public.people(id),
  action text NOT NULL,
  table_name text NOT NULL,
  record_id uuid,
  before jsonb,
  after jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.preapproved_emails (
  email text PRIMARY KEY CHECK (email = lower(email)),
  note text,
  consumed_by uuid REFERENCES public.people(id),
  consumed_at timestamptz
);

CREATE TABLE public.sequences (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  offset_days int NOT NULL,
  audience_states text[] NOT NULL,
  active boolean NOT NULL DEFAULT false
);

CREATE TABLE public.sends (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NOT NULL REFERENCES public.people(id) ON DELETE CASCADE,
  sequence_id uuid NOT NULL REFERENCES public.sequences(id),
  sent_at timestamptz DEFAULT now(),
  opened_at timestamptz,
  bounced boolean NOT NULL DEFAULT false,
  bounce_type text CHECK (bounce_type IN ('hard','soft')),
  complained boolean NOT NULL DEFAULT false,
  UNIQUE (person_id, sequence_id)
);

CREATE TABLE public.suppressions (
  email text PRIMARY KEY CHECK (email = lower(email)),
  reason text NOT NULL,
  created_at timestamptz DEFAULT now()
);

INSERT INTO public.sequences (key, offset_days, audience_states, active) VALUES
  ('t_minus_60', -60, ARRAY['unclaimed','claimed'], false),
  ('t_minus_42', -42, ARRAY['unclaimed','claimed'], false),
  ('t_minus_28', -28, ARRAY['unclaimed','claimed'], false),
  ('t_minus_21', -21, ARRAY['unclaimed'], false),
  ('t_minus_14', -14, ARRAY['unclaimed','claimed','maybe'], false),
  ('t_minus_7', -7, ARRAY['claimed','maybe','going'], false),
  ('t_minus_2', -2, ARRAY['going','maybe'], false),
  ('t_plus_3', 3, ARRAY['going','maybe','claimed','unclaimed'], false);

CREATE OR REPLACE FUNCTION public.current_person_id()
RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT person_id FROM public.identities
  WHERE auth_user_id = auth.uid()
  ORDER BY is_primary DESC
  LIMIT 1
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admins a
    WHERE a.person_id = public.current_person_id()
  )
$$;

GRANT SELECT (
  id, member_no, seed_id, first_name, last_name, played_as, current_city, grad_year,
  seed_division, seed_division_alt, deceased, deceased_confirmed_by, deceased_confirmed_at,
  show_on_board, share_email, open_to_network, needs_review, created_at
) ON public.people TO authenticated;
GRANT UPDATE (
  first_name, last_name, played_as, current_city, grad_year,
  show_on_board, share_email, open_to_network
) ON public.people TO authenticated;
GRANT ALL ON public.people TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.identities TO authenticated;
GRANT ALL ON public.identities TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.stints TO authenticated;
GRANT ALL ON public.stints TO service_role;

GRANT SELECT ON public.events TO anon, authenticated;
GRANT ALL ON public.events TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.rsvps TO authenticated;
GRANT ALL ON public.rsvps TO service_role;

GRANT SELECT, INSERT ON public.suggestions TO authenticated;
GRANT ALL ON public.suggestions TO service_role;

GRANT SELECT, INSERT, DELETE ON public.verifications TO authenticated;
GRANT ALL ON public.verifications TO service_role;

GRANT SELECT ON public.admins TO authenticated;
GRANT ALL ON public.admins TO service_role;

GRANT SELECT ON public.audit_log TO authenticated;
GRANT ALL ON public.audit_log TO service_role;

GRANT SELECT ON public.preapproved_emails TO authenticated;
GRANT ALL ON public.preapproved_emails TO service_role;

GRANT SELECT ON public.sequences TO authenticated;
GRANT ALL ON public.sequences TO service_role;
GRANT SELECT ON public.sends TO authenticated;
GRANT ALL ON public.sends TO service_role;
GRANT SELECT ON public.suppressions TO authenticated;
GRANT ALL ON public.suppressions TO service_role;

ALTER TABLE public.people ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rsvps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preapproved_emails ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sends ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppressions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "signed in members read roster" ON public.people
  FOR SELECT TO authenticated USING (show_on_board OR id = public.current_person_id() OR public.is_admin());
CREATE POLICY "members update own record" ON public.people
  FOR UPDATE TO authenticated USING (id = public.current_person_id()) WITH CHECK (id = public.current_person_id());
CREATE POLICY "admins manage people" ON public.people
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY "own identities" ON public.identities
  FOR SELECT TO authenticated USING (person_id = public.current_person_id() OR public.is_admin());
CREATE POLICY "admins manage identities" ON public.identities
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY "members read stints" ON public.stints
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "members add own past stints" ON public.stints
  FOR INSERT TO authenticated
  WITH CHECK (person_id = public.current_person_id() AND year <> EXTRACT(YEAR FROM now())::int);
CREATE POLICY "members edit own past stints" ON public.stints
  FOR UPDATE TO authenticated
  USING (person_id = public.current_person_id() AND year <> EXTRACT(YEAR FROM now())::int)
  WITH CHECK (person_id = public.current_person_id() AND year <> EXTRACT(YEAR FROM now())::int);
CREATE POLICY "members delete own past stints" ON public.stints
  FOR DELETE TO authenticated
  USING (person_id = public.current_person_id() AND year <> EXTRACT(YEAR FROM now())::int);
CREATE POLICY "admins manage stints" ON public.stints
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY "events readable by everyone" ON public.events
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "admins manage events" ON public.events
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY "members read rsvps" ON public.rsvps
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "members write own rsvp" ON public.rsvps
  FOR INSERT TO authenticated WITH CHECK (person_id = public.current_person_id());
CREATE POLICY "members update own rsvp" ON public.rsvps
  FOR UPDATE TO authenticated USING (person_id = public.current_person_id()) WITH CHECK (person_id = public.current_person_id());
CREATE POLICY "members delete own rsvp" ON public.rsvps
  FOR DELETE TO authenticated USING (person_id = public.current_person_id());
CREATE POLICY "admins manage rsvps" ON public.rsvps
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY "members read own suggestions" ON public.suggestions
  FOR SELECT TO authenticated USING (submitted_by = public.current_person_id() OR public.is_admin());
CREATE POLICY "members submit suggestions" ON public.suggestions
  FOR INSERT TO authenticated WITH CHECK (submitted_by = public.current_person_id());
CREATE POLICY "admins manage suggestions" ON public.suggestions
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY "members read verifications" ON public.verifications
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "members verify others" ON public.verifications
  FOR INSERT TO authenticated WITH CHECK (verified_by = public.current_person_id());
CREATE POLICY "members remove own verification" ON public.verifications
  FOR DELETE TO authenticated USING (verified_by = public.current_person_id());

CREATE POLICY "admins read admins" ON public.admins
  FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY "admins manage admins" ON public.admins
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY "admins read audit log" ON public.audit_log
  FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY "admins manage preapproved" ON public.preapproved_emails
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "admins manage sequences" ON public.sequences
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "admins manage sends" ON public.sends
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "admins manage suppressions" ON public.suppressions
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE VIEW public.person_board_placement AS
SELECT
  p.id AS person_id,
  COALESCE((SELECT max(s.year) FROM public.stints s WHERE s.person_id = p.id), p.grad_year) AS board_year,
  COALESCE(
    (SELECT s.division FROM public.stints s WHERE s.person_id = p.id ORDER BY s.year DESC, s.division LIMIT 1),
    p.seed_division
  ) AS board_division,
  (SELECT count(*) FROM public.stints s WHERE s.person_id = p.id) AS stint_count
FROM public.people p;

CREATE VIEW public.current_players AS
SELECT DISTINCT s.person_id, s.year, s.division
FROM public.stints s
WHERE s.source IN ('roster_import','self','admin');

CREATE VIEW public.board_people AS
SELECT
  p.id,
  p.first_name,
  p.last_name,
  p.played_as,
  p.deceased,
  pbp.board_year,
  pbp.board_division,
  tn.name AS team_label,
  CASE
    WHEN p.deceased THEN 'memorial'
    WHEN r.status = 'going' THEN 'going'
    WHEN r.status = 'maybe' THEN 'maybe'
    WHEN EXISTS (SELECT 1 FROM public.identities i WHERE i.person_id = p.id AND i.verified_at IS NOT NULL) THEN 'claimed'
    ELSE 'unclaimed'
  END AS state
FROM public.people p
JOIN public.person_board_placement pbp ON pbp.person_id = p.id
LEFT JOIN public.rsvps r ON r.person_id = p.id AND r.event_year = 2026
LEFT JOIN public.team_names tn
  ON tn.division = pbp.board_division
 AND pbp.board_year BETWEEN COALESCE(tn.start_year, -2147483648) AND COALESCE(tn.end_year, 2147483647)
WHERE p.show_on_board = true AND pbp.board_year IS NOT NULL;

CREATE VIEW public.board_year_counts AS
SELECT
  board_year,
  count(*)::int AS total,
  (count(*) FILTER (WHERE state IN ('claimed','going','maybe')))::int AS claimed,
  (count(*) FILTER (WHERE state = 'going'))::int AS going
FROM public.board_people
GROUP BY board_year;

CREATE VIEW public.identities_needing_second_email AS
SELECT id, person_id, email
FROM public.identities
WHERE email LIKE '%@pitt.edu' AND email NOT LIKE '%@alumni.pitt.edu';

GRANT SELECT ON public.board_people TO anon, authenticated;
GRANT SELECT ON public.board_year_counts TO anon, authenticated;
GRANT SELECT ON public.person_board_placement TO authenticated;
GRANT SELECT ON public.current_players TO authenticated;
GRANT SELECT ON public.identities_needing_second_email TO service_role;